version: 2

models:
  - name: full_names
    description: Creates a full_name column from first and last name
    columns:
      - name: id
        description: Primary key
        tests:
          - not_null
          - unique

      - name: full_name
        description: Concatenated first and last name
        tests:
          - not_null

